import type sanitizeHtml from 'sanitize-html';

export const sanitizeOptions: sanitizeHtml.IOptions = {
  allowedTags: [
    // Headings
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    // Text formatting
    'p',
    'div',
    'span',
    'br',
    'hr',
    'pre',
    'code',
    // Text styles
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'strike',
    'del',
    'mark',
    'small',
    'sub',
    'sup',
    // Lists
    'blockquote',
    'ol',
    'ul',
    'li',
    'dl',
    'dt',
    'dd',
    // Links and media
    'a',
    'img',
    'video',
    'audio',
    'source',
    'iframe',
    'figure',
    'figcaption',
    // Tables
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    'caption',
    'col',
    'colgroup',
    // Semantic HTML5
    'section',
    'article',
    'aside',
    'header',
    'footer',
    'nav',
    'main',
    // Forms (если нужны)
    'form',
    'input',
    'textarea',
    'button',
    'select',
    'option',
    'label',
    'fieldset',
    'legend',
    // Other
    'details',
    'summary',
    'dialog',
    'canvas',
    'svg',
    'path',
    'circle',
    'rect',
    'line',
    'polyline',
    'polygon',
    'g',
    'defs',
    'use',
    // Styling
    'style',
    'link',
  ],
  allowedAttributes: {
    'a': ['href', 'name', 'target', 'rel', 'title', 'id', 'class', 'style', 'download'],
    'img': [
      'src',
      'alt',
      'width',
      'height',
      'loading',
      'title',
      'id',
      'class',
      'style',
      'srcset',
      'sizes',
    ],
    'iframe': [
      'src',
      'width',
      'height',
      'frameborder',
      'allow',
      'allowfullscreen',
      'loading',
      'title',
      'id',
      'class',
      'style',
      'sandbox',
    ],
    'video': [
      'src',
      'controls',
      'width',
      'height',
      'autoplay',
      'loop',
      'muted',
      'poster',
      'preload',
      'id',
      'class',
      'style',
      'playsinline',
    ],
    'audio': ['src', 'controls', 'autoplay', 'loop', 'muted', 'preload', 'id', 'class', 'style'],
    'source': ['src', 'type', 'media'],
    'table': ['border', 'cellpadding', 'cellspacing', 'id', 'class', 'style'],
    'th': ['colspan', 'rowspan', 'scope', 'id', 'class', 'style'],
    'td': ['colspan', 'rowspan', 'id', 'class', 'style'],
    'ol': ['start', 'type', 'id', 'class', 'style', 'reversed'],
    'ul': ['id', 'class', 'style'],
    'li': ['id', 'class', 'style', 'value'],
    'code': ['class', 'id', 'style'],
    'pre': ['class', 'id', 'style'],
    'style': ['type', 'media'],
    'link': ['rel', 'href', 'type', 'media'],
    'button': ['type', 'id', 'class', 'style', 'disabled', 'name', 'value'],
    'input': [
      'type',
      'id',
      'class',
      'style',
      'name',
      'value',
      'placeholder',
      'disabled',
      'readonly',
      'required',
      'min',
      'max',
      'step',
      'pattern',
      'checked',
    ],
    'textarea': [
      'id',
      'class',
      'style',
      'name',
      'placeholder',
      'rows',
      'cols',
      'disabled',
      'readonly',
      'required',
    ],
    'select': ['id', 'class', 'style', 'name', 'disabled', 'required', 'multiple'],
    'option': ['value', 'selected', 'disabled'],
    'label': ['for', 'id', 'class', 'style'],
    'form': ['action', 'method', 'id', 'class', 'style'],
    'canvas': ['width', 'height', 'id', 'class', 'style'],
    'svg': ['width', 'height', 'viewBox', 'id', 'class', 'style', 'xmlns'],
    'path': ['d', 'fill', 'stroke', 'stroke-width', 'id', 'class', 'style'],
    'circle': ['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width', 'id', 'class', 'style'],
    'rect': ['x', 'y', 'width', 'height', 'fill', 'stroke', 'stroke-width', 'rx', 'ry', 'id', 'class', 'style'],
    'line': ['x1', 'y1', 'x2', 'y2', 'stroke', 'stroke-width', 'id', 'class', 'style'],
    'g': ['id', 'class', 'style', 'transform'],
    '*': ['style', 'class', 'id', 'data-*', 'aria-*', 'role'],
  },
  allowedSchemesByTag: {
    img: ['http', 'https', 'data', 'blob'],
    a: ['http', 'https', 'mailto', 'tel', 'sms'],
    iframe: ['http', 'https'],
    video: ['http', 'https', 'data', 'blob'],
    audio: ['http', 'https', 'data', 'blob'],
    source: ['http', 'https', 'data', 'blob'],
    link: ['http', 'https'],
  },
  allowProtocolRelative: true,

  allowedStyles: {
    '*': {
      '*': [/^.*$/],
    },
  },

  allowedClasses: {
    '*': ['*'],
  },

  allowedSchemes: ['http', 'https', 'data', 'blob', 'mailto', 'tel', 'sms'],

  transformTags: {
    b: 'strong',
    i: 'em',
  },

  nonTextTags: ['style', 'textarea', 'option', 'noscript'],

  exclusiveFilter(_frame: any) {
    return false;
  },
};
